name: get_calley
description: Get Calley - Call Management Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_inappwebview: ^6.1.5

  # State Management
  provider: ^6.1.1

  # Network
  dio: ^5.4.0

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Charts
  fl_chart: ^1.1.1

  # YouTube Player
  youtube_player_flutter: ^9.1.3

  # URL Launcher
  url_launcher: ^6.2.2

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

