name: get_calley_test
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.10
  youtube_player_flutter: ^8.1.0
  fl_chart: ^0.60.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true